[build]
  functions = "./functions"
  command = "npm run build"

[dev]
  port = 3000
  publish = "/dist"
  command = "npm run dev"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
